name = "functions-alex-tran-org"
pages_build_output_dir = "./dist"
compatibility_date = "2025-05-22"

[vars]
NEWSLETTER_LIST_ID = "fab659c9-d6bc-440e-894b-bb7d15943f93"
NEWSLETTER_API_KEY = "mc_pMklHPRtVBS189EU1sJ2yyebWSmCcyhRAybbxEGJ87438999"
SUBSCRIPTION_SUCCESS_MESSAGE = "Yee-haw, thanks for subscribing! Let me underpromise an email a month and hopefully overdeliver on it."
SUBSCRIPTION_FAILED_MESSAGE = "An unexpected error happened subscribing. Try again and if it continues, could you do me a favor and reach out via my contact page? Thanks!"
URL = "https://www.alextran.org"
